title: Lots Doin
name: Lots Doin's homepage
description:  尝试着将思考记录下来.
url: https://lotsdoin.github.io
email: lotsdoin@gmail.com

# 自定义post url
permalink: /blog/:title.html
timezone: Asia/Shanghai

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

markdown: kramdown
kramdown:
    input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
    extensions:
    - autolink
    - footnotes
    - smart
hard_wrap: false
#  use_coderay: true
syntax_highlighter: rouge
#  coderay:
#  coderay_line_numbers:  nil

# White-listed plugins
#gems:
plugins:
  - jekyll-sitemap
